package pandaderia;

import Models.CorteModel;
import Models.Empleado;
import java.awt.Color;
import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import java.awt.Component;

public class Menu extends javax.swing.JFrame {
    
    private Empleado empleadoLoggeado;
    private CorteModel currentCorte;
    private Venta ventanaVenta;
    private MisEmpleados ventanaEmpleados;
    private Inventario ventanaInventario;
    private Corte ventanaCorte;
    private CorteAdmin ventanaCorteAdmin;
    private Login ventanaLogin;
    private RegProveedor ventanaRegProveedor;
    private Conexion conexion;
    
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Menu");
        setResizable(false);
    }
    
    public Menu(Component father,Empleado logged) { //aqui  sobreescribo el constructor
        empleadoLoggeado = logged;
        
        initComponents();
        Empleados.setVisible(empleadoLoggeado.getRol() == 1);
        this.setLocationRelativeTo(father);
        //System.out.println(empleadoLoggeado.toString());
    }
    
    public Menu(Login previewView, Empleado emp, CorteModel currentCorte,Conexion cc){
        conexion = cc;
        empleadoLoggeado = emp;
        this.currentCorte = currentCorte;
        initComponents();
        Empleados.setVisible(empleadoLoggeado.getRol() == 1);
        Venta.setVisible(empleadoLoggeado.getRol() == 2);
        proveedoresJBtn.setVisible(empleadoLoggeado.getRol() == 2);
        //Inventario.setVisible(empleadoLoggeado.getRol() == 1);
        setTitle("Menu");
        setLocationRelativeTo(previewView);
        this.ventanaLogin = previewView;
        this.setVisible(rootPaneCheckingEnabled);
        setResizable(false);
        //this.getContentPane().setBackground(Color.YELLOW);
    }

    public void thismissVentas(){
        System.out.println(empleadoLoggeado);
        ventanaVenta.setVisible(false);
        this.setVisible(true);
        ventanaVenta = null;
    }
    public void thismissEmpleados(){
        System.out.println(empleadoLoggeado);
        ventanaEmpleados.setVisible(false);
        this.setVisible(true);
        ventanaEmpleados = null;
    }
    public void thismissCorteEmpleadoViewer(CorteModel corteActualizado){
        System.out.println(empleadoLoggeado);
        ventanaCorte.setVisible(false);
        this.setVisible(true);
        ventanaCorte = null;
        currentCorte = corteActualizado;
        if(currentCorte.getEstatus() == 1){
            Venta.setEnabled(false);
            proveedoresJBtn.setEnabled(false);
            Inventario.setEnabled(false);
        }
    }
    public void thismissCorteAdminViewer(){
        ventanaCorteAdmin.setVisible(false);
        this.setVisible(true);
        ventanaCorteAdmin = null;
        
    }
    public void thismissRegProveedor(){
        ventanaRegProveedor.setVisible(false);
        this.setVisible(true);
        ventanaRegProveedor = null;
    }
    public void thismissInventario(){
        System.out.println(empleadoLoggeado);
        ventanaInventario.setVisible(false);
        this.setVisible(true);
        ventanaInventario = null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        proveedoresJBtn = new javax.swing.JButton();
        Venta = new javax.swing.JButton();
        Inventario = new javax.swing.JButton();
        Corte = new javax.swing.JButton();
        Empleados = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 15))); // NOI18N

        proveedoresJBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconfinder_suppliers_54466(1).png"))); // NOI18N
        proveedoresJBtn.setText("Proveedores");
        proveedoresJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresJBtnActionPerformed(evt);
            }
        });

        Venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venta.png"))); // NOI18N
        Venta.setText("Venta");
        Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaActionPerformed(evt);
            }
        });

        Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventario.png"))); // NOI18N
        Inventario.setText("Inventario");
        Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioActionPerformed(evt);
            }
        });

        Corte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coin.png"))); // NOI18N
        Corte.setText("Corte");
        Corte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorteActionPerformed(evt);
            }
        });

        Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/empleados.png"))); // NOI18N
        Empleados.setText("Empleados");
        Empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpleadosMouseClicked(evt);
            }
        });
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });

        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconfinder_outlined_log_out_4280468.png"))); // NOI18N
        LogOut.setText("Cerrar sesion");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proveedoresJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Corte, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogOut)))
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proveedoresJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Corte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOut)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioActionPerformed
        ventanaInventario = new Inventario(this, empleadoLoggeado);
        System.out.println(empleadoLoggeado);
        ventanaInventario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InventarioActionPerformed

    private void EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosActionPerformed
        ventanaEmpleados = new MisEmpleados(this, empleadoLoggeado);
        System.out.println(empleadoLoggeado);
        ventanaEmpleados.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EmpleadosActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        
        ventanaLogin.setVisible(true);
        this.setVisible(false);
        ventanaLogin.dissmisMenu();
        //this.setVisible(false);
    }//GEN-LAST:event_LogOutActionPerformed

    private void EmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpleadosMouseClicked

    }//GEN-LAST:event_EmpleadosMouseClicked

    private void CorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorteActionPerformed
        if(empleadoLoggeado.getRol() == 1){ //ADMIN
            ventanaCorteAdmin = new CorteAdmin(this, conexion, empleadoLoggeado);
            ventanaCorteAdmin.setVisible(true);
            this.setVisible(false);
        }else{
            ventanaCorte = new Corte(this,currentCorte,conexion);
            System.out.println(empleadoLoggeado);
            ventanaCorte.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_CorteActionPerformed

    private void VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaActionPerformed
        ventanaVenta = new Venta(this, empleadoLoggeado, conexion, currentCorte);
        System.out.println(empleadoLoggeado);
        ventanaVenta.setVisible(true); //this,logueado
        this.setVisible(false);
    }//GEN-LAST:event_VentaActionPerformed

    private void proveedoresJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresJBtnActionPerformed
        ventanaRegProveedor = new RegProveedor(this, empleadoLoggeado, conexion, currentCorte);
        System.out.println(empleadoLoggeado);
        ventanaRegProveedor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_proveedoresJBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Corte;
    private javax.swing.JButton Empleados;
    private javax.swing.JButton Inventario;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton Venta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton proveedoresJBtn;
    // End of variables declaration//GEN-END:variables

  
}
