/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pandaderia;

import Models.Clientes;
import Models.Empleado;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author alexis
 */
public class NuevoProveedor extends javax.swing.JFrame {

    private Empleado empleadoLoggeado;
    private RegProveedor ventanaRegProveedor;
    
    
    public NuevoProveedor() {
        initComponents();
        setTitle("Nuevo cliente");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public NuevoProveedor(RegProveedor previewView, Empleado emp){
        initComponents();
        setLocationRelativeTo(previewView);
        this.ventanaRegProveedor = previewView;
        setTitle("Nuevo proveedor");
        empleadoLoggeado = emp;
        setResizable(false);
    }
    
    public void limpiaVentana(){
        NomClientJtf.setText("");
        PaternoClientJtf.setText("");
        MaternoClientJtf.setText("");
        TelClientJtf.setText("");
        emailClientJtf.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NomClientJtf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PaternoClientJtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MaternoClientJtf = new javax.swing.JTextField();
        AddProveedorJBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TelClientJtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailClientJtf = new javax.swing.JTextField();
        cancelarJBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Nombre: ");

        NomClientJtf.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        NomClientJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomClientJtfActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setText("A Paterno: ");

        PaternoClientJtf.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setText("A Materno:");

        MaternoClientJtf.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N

        AddProveedorJBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addUser.png"))); // NOI18N
        AddProveedorJBtn.setText("Agregar proveedor");
        AddProveedorJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProveedorJBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setText("Teléfono:");

        TelClientJtf.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setText("Correo:");

        emailClientJtf.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N

        cancelarJBtn.setText("Cancelar");
        cancelarJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelClientJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaternoClientJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailClientJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PaternoClientJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomClientJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelarJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddProveedorJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NomClientJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PaternoClientJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MaternoClientJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(TelClientJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailClientJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddProveedorJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cancelarJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomClientJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomClientJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomClientJtfActionPerformed

    private void AddProveedorJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProveedorJBtnActionPerformed
        Conexion cc = new Conexion();
        
        if((NomClientJtf.getText().isEmpty()) 
                || (PaternoClientJtf.getText().isEmpty()) 
                || (TelClientJtf.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
        }else{
          
                    Clientes nuevoCliente = new Clientes();
                    nuevoCliente.setnombre(NomClientJtf.getText());
                    nuevoCliente.setAppPat(PaternoClientJtf.getText());
                    nuevoCliente.setAppMat(MaternoClientJtf.getText());
                    nuevoCliente.setTelefono(TelClientJtf.getText());
                    nuevoCliente.setCorreo(emailClientJtf.getText());
            try {
                    PreparedStatement pst= cc.conectar.prepareStatement("INSERT INTO Cliente (nombre, paterno, materno, telefono, correo, empresa) VALUES(?,?,?,?,?, ? )",Statement.RETURN_GENERATED_KEYS);       

                    pst.setString(1,nuevoCliente.getnombre() );
                    pst.setString(2,nuevoCliente.getAppPat() ); 
                    pst.setString(3,nuevoCliente.getAppMat() );
                    pst.setString(4,nuevoCliente.getTelefono() );
                    pst.setString(5,nuevoCliente.getCorreo() );
                    pst.setString(6,nuevoCliente.getEmpresa() );
                    pst.execute();
                    
                    ResultSet idCreated = pst.getGeneratedKeys();
                    if(idCreated.next()){
                        int idCliente = idCreated.getInt(1);
                        nuevoCliente.setIdCliente(idCliente);
                    }

                    JOptionPane.showMessageDialog(null, "GUARDADO");                    
                    //ventanaRegProveedor.seleccionaNuevoClienteRegistrado(nuevoCliente);
                    
                
            }catch (SQLException e) {
                //System.out.println(e);
                JOptionPane.showMessageDialog(null, "ERROR");
            }
        }    
    }//GEN-LAST:event_AddProveedorJBtnActionPerformed

    private void cancelarJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJBtnActionPerformed
        // TODO add your handling code here:
        ventanaRegProveedor.thismissNewProveedor();
    }//GEN-LAST:event_cancelarJBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProveedorJBtn;
    private javax.swing.JTextField MaternoClientJtf;
    private javax.swing.JTextField NomClientJtf;
    private javax.swing.JTextField PaternoClientJtf;
    private javax.swing.JTextField TelClientJtf;
    private javax.swing.JToggleButton cancelarJBtn;
    private javax.swing.JTextField emailClientJtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
